# ビルドステージ
FROM maven:3.9.5-eclipse-temurin-17-alpine AS build
WORKDIR /app

COPY pom.xml .
RUN mvn dependency:go-offline

COPY src ./src
RUN mvn clean package -DskipTests

# 実行ステージ
FROM eclipse-temurin:17-jre-alpine
WORKDIR /app

RUN apk add --no-cache curl 
RUN apk add --no-cache bash

COPY --from=build /app/target/api-gateway-0.0.1-SNAPSHOT.jar app.jar

COPY wait-for-it.sh /wait-for-it.sh
RUN chmod +x /wait-for-it.sh

ENTRYPOINT ["/wait-for-it.sh", "eureka-server:8761", "--", "bash", "-c", "java -Xmx512m -Xms256m -jar app.jar"]